### ISSUE TITLE
提交还是不要用脚本偷懒为好

### ISSUE THREAD

**Issue by jaxvanyang** [Crazyokd/Enjoy-Design-Pattern#1]
如果提交信息都是一样的，那提交信息也就没意义了。

如果每次都将所有文件提交，实验性的修改也会被提交污染仓库。

**Comment by Crazyokd** [comment]
目前该脚本只是作为本人完善该仓库的的追加提交所用，特殊的提交仍会采取手动提交。（~~仓库渐趋完善后，该脚本会被删除~~）

**Comment by Crazyokd** [comment]
后续的想法是在每个特定设计模式中采用脚本启动demo代码。

**Comment by jaxvanyang** [comment]
只是提醒一下 : )
